# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ming/Documents/PolyM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ming/Documents/PolyM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ming/Documents/PolyM/CMakeFiles /home/ming/Documents/PolyM/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ming/Documents/PolyM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named polym

# Build rule for target.
polym: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 polym
.PHONY : polym

# fast build rule for target.
polym/fast:
	$(MAKE) -f CMakeFiles/polym.dir/build.make CMakeFiles/polym.dir/build
.PHONY : polym/fast

#=============================================================================
# Target rules for targets named testpolym

# Build rule for target.
testpolym: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testpolym
.PHONY : testpolym

# fast build rule for target.
testpolym/fast:
	$(MAKE) -f CMakeFiles/testpolym.dir/build.make CMakeFiles/testpolym.dir/build
.PHONY : testpolym/fast

Msg.o: Msg.cpp.o

.PHONY : Msg.o

# target to build an object file
Msg.cpp.o:
	$(MAKE) -f CMakeFiles/polym.dir/build.make CMakeFiles/polym.dir/Msg.cpp.o
.PHONY : Msg.cpp.o

Msg.i: Msg.cpp.i

.PHONY : Msg.i

# target to preprocess a source file
Msg.cpp.i:
	$(MAKE) -f CMakeFiles/polym.dir/build.make CMakeFiles/polym.dir/Msg.cpp.i
.PHONY : Msg.cpp.i

Msg.s: Msg.cpp.s

.PHONY : Msg.s

# target to generate assembly for a file
Msg.cpp.s:
	$(MAKE) -f CMakeFiles/polym.dir/build.make CMakeFiles/polym.dir/Msg.cpp.s
.PHONY : Msg.cpp.s

Queue.o: Queue.cpp.o

.PHONY : Queue.o

# target to build an object file
Queue.cpp.o:
	$(MAKE) -f CMakeFiles/polym.dir/build.make CMakeFiles/polym.dir/Queue.cpp.o
.PHONY : Queue.cpp.o

Queue.i: Queue.cpp.i

.PHONY : Queue.i

# target to preprocess a source file
Queue.cpp.i:
	$(MAKE) -f CMakeFiles/polym.dir/build.make CMakeFiles/polym.dir/Queue.cpp.i
.PHONY : Queue.cpp.i

Queue.s: Queue.cpp.s

.PHONY : Queue.s

# target to generate assembly for a file
Queue.cpp.s:
	$(MAKE) -f CMakeFiles/polym.dir/build.make CMakeFiles/polym.dir/Queue.cpp.s
.PHONY : Queue.cpp.s

Test.o: Test.cpp.o

.PHONY : Test.o

# target to build an object file
Test.cpp.o:
	$(MAKE) -f CMakeFiles/testpolym.dir/build.make CMakeFiles/testpolym.dir/Test.cpp.o
.PHONY : Test.cpp.o

Test.i: Test.cpp.i

.PHONY : Test.i

# target to preprocess a source file
Test.cpp.i:
	$(MAKE) -f CMakeFiles/testpolym.dir/build.make CMakeFiles/testpolym.dir/Test.cpp.i
.PHONY : Test.cpp.i

Test.s: Test.cpp.s

.PHONY : Test.s

# target to generate assembly for a file
Test.cpp.s:
	$(MAKE) -f CMakeFiles/testpolym.dir/build.make CMakeFiles/testpolym.dir/Test.cpp.s
.PHONY : Test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... polym"
	@echo "... edit_cache"
	@echo "... testpolym"
	@echo "... Msg.o"
	@echo "... Msg.i"
	@echo "... Msg.s"
	@echo "... Queue.o"
	@echo "... Queue.i"
	@echo "... Queue.s"
	@echo "... Test.o"
	@echo "... Test.i"
	@echo "... Test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

